# Generated by Django 2.2.2 on 2019-11-17 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import game_collection.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_database', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='date added')),
                ('game_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game_database.GameVersion', verbose_name='game version')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlist',
            },
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Tag Group',
                'verbose_name_plural': 'Tag Groups',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Playing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adquired', models.DateField(blank=True, null=True, verbose_name='date adquired')),
                ('time_played', models.FloatField(blank=True, null=True, verbose_name='time played')),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='date started')),
                ('game_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game_database.GameVersion', verbose_name='game version')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Playing',
                'verbose_name_plural': 'Playing',
            },
        ),
        migrations.CreateModel(
            name='Played',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adquired', models.DateField(blank=True, null=True, verbose_name='date adquired')),
                ('time_played', models.FloatField(blank=True, null=True, verbose_name='time played')),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='date started')),
                ('date_stopped', models.DateField(blank=True, null=True, verbose_name='date stopped')),
                ('game_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game_database.GameVersion', verbose_name='game version')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Played',
                'verbose_name_plural': 'Played',
            },
        ),
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='date added')),
                ('game_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game_database.GameVersion', verbose_name='game version')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Interested',
                'verbose_name_plural': 'Interested',
            },
        ),
        migrations.CreateModel(
            name='Finished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adquired', models.DateField(blank=True, null=True, verbose_name='date adquired')),
                ('time_played', models.FloatField(blank=True, null=True, verbose_name='time played')),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='date started')),
                ('date_finished', models.DateField(blank=True, null=True, verbose_name='date finished')),
                ('time_to_finish', models.FloatField(blank=True, null=True, verbose_name='time to finish')),
                ('playstyle', models.CharField(choices=[(game_collection.models.PlaystyleChoice('Main Story'), 'Main Story'), (game_collection.models.PlaystyleChoice('Main + Extra'), 'Main + Extra'), (game_collection.models.PlaystyleChoice('Completionist'), 'Completionist')], max_length=5, verbose_name='playstyle')),
                ('game_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game_database.GameVersion', verbose_name='game version')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Finished',
                'verbose_name_plural': 'Finished',
            },
        ),
        migrations.CreateModel(
            name='Abandoned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adquired', models.DateField(blank=True, null=True, verbose_name='date adquired')),
                ('time_played', models.FloatField(blank=True, null=True, verbose_name='time played')),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='date started')),
                ('date_abandoned', models.DateField(blank=True, null=True, verbose_name='date abandoned')),
                ('game_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game_database.GameVersion', verbose_name='game version')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Abandoned',
                'verbose_name_plural': 'Abandoned',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='name')),
                ('game_version', models.ManyToManyField(to='game_database.GameVersion', verbose_name='game version')),
                ('tag_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_collection.TagGroup', verbose_name='tag group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adquired', models.DateField(blank=True, null=True, verbose_name='date adquired')),
                ('time_played', models.FloatField(blank=True, null=True, verbose_name='time played')),
                ('game_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game_database.GameVersion', verbose_name='game version')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'game_version')},
            },
        ),
    ]
