# Generated by Django 2.2.2 on 2019-12-15 20:08

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_database', '0001_initial'),
        ('game_collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=5, verbose_name='score')),
                ('text', models.TextField(verbose_name='text')),
                ('date',
                 models.DateField(default=datetime.datetime(2019, 12, 15, 21, 8, 37, 936246), verbose_name='date')),
                ('game_version',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_database.GameVersion',
                                   verbose_name='game version')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='user')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'unique_together': {('user', 'game_version')},
            },
        ),
    ]
