# Generated by Django 2.2.2 on 2019-11-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abandoned',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='finished',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='played',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='playing',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='queue',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='price'),
        ),
    ]
