# Generated by Django 2.2.7 on 2019-12-22 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_collection', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 22, 18, 0, 57, 459013), verbose_name='date'),
        ),
    ]
