# Generated by Django 2.2.7 on 2019-12-22 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_collection', '0003_auto_20191222_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 22, 18, 3, 57, 905611), verbose_name='date'),
        ),
    ]
