# Generated by Django 2.2.2 on 2019-11-17 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('db_id', models.CharField(max_length=16, unique=True, verbose_name='DB ID')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='title')),
                ('db_id', models.CharField(max_length=16, unique=True, verbose_name='DB ID')),
                ('main_time', models.FloatField(default=0, verbose_name='main time')),
                ('extra_time', models.FloatField(default=0, verbose_name='extra time')),
                ('completion_time', models.FloatField(default=0, verbose_name='completion time')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='release date')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('img_url', models.CharField(blank=True, max_length=128, verbose_name='image url')),
                ('update', models.BooleanField(default=True, verbose_name='update')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('db_id', models.CharField(max_length=16, unique=True, verbose_name='DB ID')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='name')),
                ('db_id', models.CharField(max_length=16, unique=True, verbose_name='DB ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('img_url', models.CharField(blank=True, max_length=128, verbose_name='image url')),
                ('update', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
            },
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='release date')),
                ('db_id', models.CharField(max_length=16)),
                ('update', models.BooleanField(default=True)),
                ('developers', models.ManyToManyField(related_name='developers', to='game_database.Company', verbose_name='developers')),
                ('parent_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_database.Game')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_database.Platform')),
                ('publishers', models.ManyToManyField(related_name='publishers', to='game_database.Company', verbose_name='publishers')),
            ],
            options={
                'verbose_name': 'Game Version',
                'verbose_name_plural': 'Game Versions',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='game_database.Genre', verbose_name='genres'),
        ),
    ]
