# Generated by Django 2.2.2 on 2019-11-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='db_id',
            field=models.CharField(default=1, max_length=16, unique=True, verbose_name='DB ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='platform',
            name='img_url',
            field=models.CharField(blank=True, max_length=128, verbose_name='image url'),
        ),
        migrations.AddField(
            model_name='platform',
            name='update',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='name'),
        ),
    ]
