version: '3'

services:
  gamehoarder:
    container_name: gamehoarder
    build: .
    image: gamehoarder
    ports:
      - '8000:8000'
    expose:
      - '8000'
    depends_on:
      - db
      - redis
    networks:
      - backend
  db:
    container_name: mysql_iw13
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'gamecollection'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - $HOME/.var/lib/mysql:/var/lib/mysql
    networks:
        - backend
  redis:
    container_name: redis_iw13
    image: redis
    ports:
    - '6379:6379'
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
