# Generated by Django 2.2.7 on 2019-12-22 21:42

from django.contrib.auth.models import Permission, Group
from django.db import migrations


def add_group_permissions(apps, schema_editor):
    # standard
    Group.objects.get_or_create(name='standard_user')

    # admin
    group, created = Group.objects.get_or_create(name='admin')
    if created:
        group.permissions.add(Permission.objects.get(name="Can change user"))
        group.permissions.add(Permission.objects.get(name="Can delete user"))
        group.permissions.add(Permission.objects.get(name="Can view user"))


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gamehoarder_site", "0001_initial")
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
