# Generated by Django 2.2.7 on 2019-12-04 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gamehoarder_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehoarder_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/user.png', storage=gamehoarder_site.models.MediaFileSystemStorage(), upload_to='avatars', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='friends'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
