# Generated by Django 2.2.2 on 2019-12-15 20:08
from django.contrib.auth.models import Group, Permission
from django.db import migrations


def add_group_permissions(apps, schema_editor):
    # standard
    Group.objects.get_or_create(name='standard_user')

    # admin
    group, created = Group.objects.get_or_create(name='admin')
    if created:
        group.permissions.add(Permission.objects.get(name="Can change user"))
        group.permissions.add(Permission.objects.get(name="Can delete user"))
        group.permissions.add(Permission.objects.get(name="Can view user"))


class Migration(migrations.Migration):
    dependencies = [
        ('gamehoarder_site', '0002_profile_avatar'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
