# Generated by Django 2.2.7 on 2019-12-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamehoarder_site', '0003_default_groups'),
        ('gamehoarder_site', '0002_auto_20191204_1321'),
    ]

    operations = [
    ]
