# Generated by Django 2.2.7 on 2019-12-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamehoarder_site', '0004_merge_20191222_1800'),
        ('gamehoarder_site', '0004_merge_20191222_1725'),
    ]

    operations = [
    ]
